#!/usr/bin/env bash
set -euo pipefail

# Bundle Apps — clones each app repo at its pinned commit, copies the
# server handler into worker/src/apps/, and generates the registry file.
#
# Called by CI/CD after sync-registry completes.

APPS_DIR="apps"
OUTPUT_DIR="worker/src/apps"

mkdir -p "$OUTPUT_DIR"

# Collect app IDs for registry generation
APP_IDS=()
IMPORTS=""
ENTRIES=""

for pointer_file in "$APPS_DIR"/*.json; do
  [ -f "$pointer_file" ] || continue
  app_id=$(basename "$pointer_file" .json)

  repo=$(jq -r '.repo' "$pointer_file")
  commit=$(jq -r '.versions[-1].commit' "$pointer_file")

  if [ "$commit" = "null" ] || [ "$commit" = "PENDING" ]; then
    echo "⏭  Skipping $app_id (commit is PENDING)"
    continue
  fi

  echo "📦 Bundling $app_id from $repo@${commit:0:8}..."

  # Clone at pinned commit
  tmpdir=$(mktemp -d)
  git clone --depth=100 "$repo.git" "$tmpdir" 2>/dev/null || {
    echo "  ❌ Failed to clone $repo"
    rm -rf "$tmpdir"
    continue
  }
  cd "$tmpdir"
  git checkout "$commit" 2>/dev/null || {
    echo "  ❌ Commit $commit not found"
    cd - > /dev/null
    rm -rf "$tmpdir"
    continue
  }
  cd - > /dev/null

  # Find the server entry point
  server_file=""
  for candidate in server.ts src/index.ts index.ts; do
    if [ -f "$tmpdir/$candidate" ]; then
      server_file="$tmpdir/$candidate"
      break
    fi
  done

  if [ -z "$server_file" ]; then
    echo "  ❌ No server entry point found"
    rm -rf "$tmpdir"
    continue
  fi

  # Copy and patch: make handleMcp exported, remove default export
  cp "$server_file" "$OUTPUT_DIR/$app_id.ts"

  # Patch the file: export handleMcp, remove default export
  python3 -c "
import re, sys
with open('$OUTPUT_DIR/$app_id.ts', 'r') as f:
    content = f.read()
# Make handleMcp exported
content = content.replace('async function handleMcp', 'export async function handleMcp')
# Remove export default { fetch... }; block
content = re.sub(
    r'\n*//[^\n]*Worker Entry Point[^\n]*\n+export default \{.*?\};?\s*$',
    '\n// Exported as handleMcp — called by the registry worker.\n',
    content,
    flags=re.DOTALL
)
with open('$OUTPUT_DIR/$app_id.ts', 'w') as f:
    f.write(content)
"

  APP_IDS+=("$app_id")
  # Convert app_id with hyphens to valid JS identifier
  js_id=$(echo "$app_id" | sed 's/-/_/g')
  IMPORTS="${IMPORTS}import { handleMcp as ${js_id} } from './${app_id}'\n"
  ENTRIES="${ENTRIES}  '${app_id}': ${js_id},\n"

  rm -rf "$tmpdir"
  echo "  ✅ $app_id bundled"
done

# Generate registry.ts
echo "📝 Generating $OUTPUT_DIR/registry.ts with ${#APP_IDS[@]} apps..."

{
  echo '/**'
  echo ' * Auto-generated app handler registry.'
  echo ' * DO NOT EDIT — regenerated by scripts/bundle-apps.sh during CI/CD.'
  echo ' */'
  echo ''
  echo -e "$IMPORTS"
  echo 'export const APP_HANDLERS: Record<string, (request: Request) => Promise<Response>> = {'
  echo -e "$ENTRIES"
  echo '}'
} > "$OUTPUT_DIR/registry.ts"

echo "✅ Bundle complete: ${APP_IDS[*]}"
