/**
 * Auto-generated app handler registry.
 * DO NOT EDIT — regenerated by scripts/bundle-apps.sh during CI/CD.
 */

import { handleMcp as devtools } from './devtools'
import { handleMcp as mercadolibre } from './mercadolibre'

export const APP_HANDLERS: Record<string, (request: Request) => Promise<Response>> = {
  'devtools': devtools,
  'mercadolibre': mercadolibre,

}
